version: 2

jobs:
  build:
    environment: &project_env
      CONTAINER_NAME: quay.io/redsift/baseos-alpine
      CIRCLE_REVERSE_DEPENDENCIES: buildos-go-alpine
      UPSTREAM_VERSION: "3.17"

    docker:
      - image: cimg/base:2023.01

    steps:
      - checkout
      - setup_remote_docker
      - run: docker login -u $QUAY_USER -p $QUAY_PASS quay.io
      - run:
          name: Build container
          command: |
            VERSION=$(git describe --exact-match --tags 2>/dev/null || git rev-parse --short HEAD)
            docker build --build-arg=VERSION=$UPSTREAM_VERSION -t ${CONTAINER_NAME} -f Dockerfile .
            for TAG in $VERSION $CIRCLE_BRANCH $UPSTREAM_VERSION; do
              docker tag ${CONTAINER_NAME}:latest ${CONTAINER_NAME}:${TAG}
            done

      - run:
          name: Test container
          command: |
            docker run --entrypoint=sh -d ${CONTAINER_NAME} true

      - run:
          name: Push container to the registry
          command: |
            docker push ${CONTAINER_NAME}

      - run:
          name: Trigger builds of dependent projects
          command: |
            PROJECTS=${CIRCLE_REVERSE_DEPENDENCIES}
            for PROJECT in ${PROJECTS}; do
              echo "\"${PROJECT}\""
              curl -X POST \
                --header 'Content-Type: application/json' \
                -d '{"branch":"master"}' \
                https://circleci.com/api/v1.1/project/github/redsift/${PROJECT}/build?circle-token=${CIRCLE_TOKEN}
            done

workflows:
  version: 2
  build:
    jobs:
      - build:
          context: org-global
